[package]
name = "discord_scraper"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = "0.15.7"
image = "0.25.6"
poise = "0.6.1"
serenity = "0.12.4"
sqlx = "0.8.6"
tokio = { version = "1.47.1", features = ["rt-multi-thread"] }
