name: Rust

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        rust_toolchain: [stable, beta, nightly]

    steps:
      - uses: actions/checkout@v5
      - name: Setup rust toolchain ${{ matrix.rust_toolchain }}
        uses: hecrj/setup-rust-action@v2
        with:
          rust-version: ${{ matrix.rust_toolchain }}
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Run build (default)
        id: default
        run: cargo build
      - name: Run build (self-bot)
        run: cargo build --no-default-features --features "self-bot"
